version: '3.4'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    environment:
      SA_PASSWORD: "Phuckhang@123"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"  

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__DefaultConnection: "Server=sqlserver;Database=SignalIr;User=sa;Password=Phuckhang@123;TrustServerCertificate=True;"
    ports:
      - "8080:8080"
    depends_on:
      - sqlserver
